name: Deploy node js application via docker compose with github actions

on:
  push:
    branches:
      - main

jobs:
  deploy:
  runs-on: ubuntu-latest

  steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Run docker compose
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.HOST || '127.0.0.1' }}
        username: ${{ secrets.USERNAME }}
        key : ${{ secrets.KEY }}
        script: |
          cd /root/my-app
          git pull origin main
          docker compose up -d
